image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch"
    develop:
      - step:
          caches:
            - pip
          script:
            - python --version
            
            # required for cfn_stack_update.py
            - pip install boto3==1.3.0

            # Run the update script to fire the required template.
            - python Src/cfn-stack-infra-common.py SJCNet-Edesia-Infra-Common Templates/sjcnet-edesia-infra-common.yml DEV